# Generated by Django 6.0.5 on 2026-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_short_intro_profile_social_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
