# Generated by Django 6.0.6 on 2026-06-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bio_remove_profile_county_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
