# Generated by Django 6.0.5 on 2026-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_county_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products/'),
        ),
    ]
