# Generated by Django 6.0.5 on 2026-05-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
