# Generated by Django 6.0.5 on 2026-05-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
