# Generated by Django 6.0.5 on 2026-05-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
